FROM golang:1.18.0-alpine3.15 as builder
WORKDIR /go/src/github.com/mendersoftware/inventory
RUN apk add --no-cache ca-certificates
COPY ./ .
RUN env CGO_ENABLED=0 go test -c -o inventory -tags main \
    -cover -covermode atomic \
    -coverpkg $(go list ./... | grep -v vendor | grep -v mocks | grep -v test | tr  '\n' ,)

FROM scratch
WORKDIR /etc/inventory
EXPOSE 8080
COPY ./config.yaml .
COPY --from=builder /go/src/github.com/mendersoftware/inventory/inventory /usr/bin/
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

STOPSIGNAL SIGINT

ENTRYPOINT ["/usr/bin/inventory", "server", "--automigrate"]
