FROM golang:1.16.2-alpine3.12 as builder
RUN mkdir -p /go/src/github.com/mendersoftware/inventory
COPY . /go/src/github.com/mendersoftware/inventory
RUN cd /go/src/github.com/mendersoftware/inventory && \
    env CGO_ENABLED=0 go test -c -o inventory-test -coverpkg $(go list ./... | grep -v vendor | grep -v mocks | grep -v test | tr  '\n' ,)

FROM alpine:3.13.1

EXPOSE 8080
RUN mkdir /tests

COPY  --from=builder /go/src/github.com/mendersoftware/inventory/inventory-test /usr/bin/
COPY ./config.yaml /usr/bin/
STOPSIGNAL SIGINT

ENTRYPOINT ["/usr/bin/inventory-test", "-test.coverprofile=/testing/coverage-acceptance.txt", "-acceptance-tests", "-test.run=TestMain", "-cli-args=server --automigrate"]
