// Copyright 2016 Mender Software AS
//
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
//
//        http://www.apache.org/licenses/LICENSE-2.0
//
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.
package main

import "github.com/stretchr/testify/mock"

// MockInventoryApp is an autogenerated mock type for the InventoryApp type
type MockInventoryApp struct {
	mock.Mock
}

// AddDevice provides a mock function with given fields: d
func (_m *MockInventoryApp) AddDevice(d *Device) error {
	ret := _m.Called(d)

	var r0 error
	if rf, ok := ret.Get(0).(func(*Device) error); ok {
		r0 = rf(d)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AddGroup provides a mock function with given fields: g
func (_m *MockInventoryApp) AddGroup(g *Group) (GroupID, error) {
	ret := _m.Called(g)

	var r0 error
	if rf, ok := ret.Get(0).(func(*Group) error); ok {
		r0 = rf(g)
	} else {
		r0 = ret.Error(0)
	}

	return GroupID("e16c71ec-1462-40ae-847d-8850f5ddffd2"), r0
}
